// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYIIvJzS2STVxwOIV3Xx6i5T_s8hCr4aE',
    appId: '1:1015999309561:web:a517a388afca24c20ce428',
    messagingSenderId: '1015999309561',
    projectId: 'catalogo-peliculas-cf431',
    authDomain: 'catalogo-peliculas-cf431.firebaseapp.com',
    storageBucket: 'catalogo-peliculas-cf431.firebasestorage.app',
    measurementId: 'G-84M2QPMDR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_al-hyPz26ikenG2c1w-K2qNKycJ5a-g',
    appId: '1:1015999309561:android:59a63990e9c6834a0ce428',
    messagingSenderId: '1015999309561',
    projectId: 'catalogo-peliculas-cf431',
    storageBucket: 'catalogo-peliculas-cf431.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN1tPQmNYyAZ95nvYXHURqS-H26wBnPHA',
    appId: '1:1015999309561:ios:5beca300495d9e5f0ce428',
    messagingSenderId: '1015999309561',
    projectId: 'catalogo-peliculas-cf431',
    storageBucket: 'catalogo-peliculas-cf431.firebasestorage.app',
    iosBundleId: 'com.example.namerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN1tPQmNYyAZ95nvYXHURqS-H26wBnPHA',
    appId: '1:1015999309561:ios:5beca300495d9e5f0ce428',
    messagingSenderId: '1015999309561',
    projectId: 'catalogo-peliculas-cf431',
    storageBucket: 'catalogo-peliculas-cf431.firebasestorage.app',
    iosBundleId: 'com.example.namerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYIIvJzS2STVxwOIV3Xx6i5T_s8hCr4aE',
    appId: '1:1015999309561:web:ec216944789f98f40ce428',
    messagingSenderId: '1015999309561',
    projectId: 'catalogo-peliculas-cf431',
    authDomain: 'catalogo-peliculas-cf431.firebaseapp.com',
    storageBucket: 'catalogo-peliculas-cf431.firebasestorage.app',
    measurementId: 'G-M4XE86DSD8',
  );
}
